# Generated by Django 3.1.7 on 2021-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRoutines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_title', models.CharField(max_length=100)),
                ('workout_type', models.CharField(max_length=100)),
                ('workout_difficulty', models.CharField(max_length=100)),
                ('workout_info', models.CharField(max_length=1000)),
                ('workout_length', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='workoutroutines',
            constraint=models.UniqueConstraint(fields=('workout_title', 'workout_info'), name='duplicate users in model not allowed for workouts'),
        ),
    ]
