# Generated by Django 3.1.7 on 2021-05-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_info',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('yoga', 'Yoga')], max_length=100),
        ),
    ]
