# Generated by Django 3.1.7 on 2021-05-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0002_auto_20210505_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=100),
        ),
    ]
