# Generated by Django 3.1.7 on 2021-05-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0003_auto_20210505_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutroutines',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'cardio'), ('strength', 'strength'), ('yoga', 'yoga')], max_length=100),
        ),
    ]
