# Generated by Django 3.1.7 on 2021-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0004_auto_20210505_0059'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutroutines',
            name='duplicate users in model not allowed for workouts',
        ),
        migrations.AddConstraint(
            model_name='workoutroutines',
            constraint=models.UniqueConstraint(fields=('workout_title', 'workout_info'), name='duplicate workout title and info not allowed for workouts model'),
        ),
    ]
