# Generated by Django 3.1.7 on 2021-04-21 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_started', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 11, 12, 502419, tzinfo=utc))),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time_posted', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 11, 12, 502710, tzinfo=utc))),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.forum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
