# Generated by Django 3.1.7 on 2021-04-21 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_auto_20210421_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 12, 20, 679005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 12, 20, 679311, tzinfo=utc)),
        ),
    ]
