# Generated by Django 3.1.7 on 2021-04-21 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0004_auto_20210421_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='real_forum',
            new_name='forum',
        ),
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 30, 44, 316448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 30, 44, 316769, tzinfo=utc)),
        ),
    ]
