# Generated by Django 3.1.7 on 2021-04-21 21:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_app', '0007_auto_20210421_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 40, 11, 575451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 21, 40, 11, 575903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
