# Generated by Django 3.1.5 on 2021-04-22 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0008_auto_20210421_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 0, 39, 21, 924242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 0, 39, 21, 939432, tzinfo=utc)),
        ),
    ]
