# Generated by Django 3.1.5 on 2021-04-22 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0009_auto_20210421_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 1, 3, 29, 159560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 1, 3, 29, 168722, tzinfo=utc)),
        ),
    ]
