# Generated by Django 3.1.7 on 2021-05-02 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0011_auto_20210422_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 20, 57, 51, 692903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 20, 57, 51, 693245, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together={('title', 'description')},
        ),
    ]
